// Hospitals and clinics in Lima — coordinates from OpenStreetMap
// Coverage: San Isidro, Miraflores, San Borja, Surco, Lince, Jesus Maria,
//           La Victoria, Surquillo, Barranco, Chorrillos, Magdalena, La Molina

export type InsuranceType =
  | 'EsSalud'
  | 'SIS'
  | 'SOAT'
  | 'Rímac'
  | 'Pacífico'
  | 'Mapfre'
  | 'BUPA'
  | 'La Positiva'
  | 'Particular'

export type FacilityType = 'hospital_publico' | 'hospital_essalud' | 'clinica_privada' | 'posta'

export interface MedicalFacility {
  id: string
  name: string
  short: string
  type: FacilityType
  lat: number
  lng: number
  address: string
  district: string
  phone?: string
  insurance: InsuranceType[]
  trauma: boolean
  pediatria: boolean
  notes?: string
}

export const FACILITIES: MedicalFacility[] = [
  {
    id: 'hospital_nacional_edgardo_reba',
    name: 'Hospital Nacional Edgardo Rebagliati Martins',
    short: 'Edgardo Rebagliati Martins',
    type: 'hospital_essalud',
    lat: -12.078364,
    lng: -77.039904,
    address: 'Avenida Edgardo Rebagliati 490',
    district: '',
    phone: '(01) 265-1526',
    insurance: ['EsSalud'],
    trauma: true,
    pediatria: true,
    notes: 'Trauma, UCI, quemados — referencia EsSalud Lima',
  },
  {
    id: 'hospital_nacional_guillermo_al',
    name: 'Hospital Nacional Guillermo Almenara Irigoyen',
    short: 'Guillermo Almenara Irigoyen',
    type: 'hospital_essalud',
    lat: -12.059579,
    lng: -77.022335,
    address: 'Avenida Almirante Miguel Grau 800',
    district: '',
    phone: '(01) 324-2983',
    insurance: ['EsSalud'],
    trauma: true,
    pediatria: true,
    notes: 'Cirugía compleja, trasplantes',
  },
  {
    id: 'hospital_iii_suarez_angamos',
    name: 'Hospital III Suarez Angamos',
    short: 'III Suarez Angamos',
    type: 'hospital_essalud',
    lat: -12.11331,
    lng: -77.028137,
    address: 'Avenida Angamos Este 261',
    district: '',
    phone: '(01) 241-2154',
    insurance: ['EsSalud'],
    trauma: true,
    pediatria: false,
    notes: 'EsSalud Miraflores/San Borja',
  },
  {
    id: 'clinica_pablo_bermudez',
    name: 'Clinica Pablo Bermudez',
    short: 'Pablo Bermudez',
    type: 'hospital_essalud',
    lat: -12.07244,
    lng: -77.038346,
    address: 'Jirón Pablo Bermudez 266',
    district: '',
    phone: '(01) 433-7933',
    insurance: ['EsSalud'],
    trauma: false,
    pediatria: false,
    notes: 'Policlínico EsSalud Jesús María',
  },
  {
    id: 'essalud_policl_nico_san_luis',
    name: 'EsSalud Policlínico San Luis',
    short: 'Policlínico San Luis',
    type: 'hospital_essalud',
    lat: -12.073207,
    lng: -76.992086,
    address: 'Avenida Circunvalación 2161',
    district: '',
    phone: '(01) 326-2599',
    insurance: ['EsSalud'],
    trauma: false,
    pediatria: false,
  },
  {
    id: 'hospital_jos__casimiro_ulloa',
    name: 'Hospital José Casimiro Ulloa',
    short: 'José Casimiro Ulloa',
    type: 'hospital_publico',
    lat: -12.1281,
    lng: -77.017742,
    address: 'Avenida Roosevelt 6355 - 6375',
    district: '',
    phone: '(01) 204-0900',
    insurance: ['SIS', 'SOAT'],
    trauma: true,
    pediatria: false,
    notes: 'Emergencias adultos — acepta sin seguro',
  },
  {
    id: 'hospital_nacional_dos_de_mayo',
    name: 'Hospital Nacional Dos de Mayo',
    short: 'Dos de Mayo',
    type: 'hospital_publico',
    lat: -12.055869,
    lng: -77.015428,
    address: 'Avenida Almirante Miguel Grau',
    district: '',
    insurance: ['SIS', 'SOAT'],
    trauma: true,
    pediatria: true,
    notes: 'Referencia MINSA — trauma',
  },
  {
    id: 'hospital_especializado_de_emer',
    name: 'Hospital Especializado de Emergencias Pediatricas',
    short: 'Especializado de Emergencias',
    type: 'hospital_publico',
    lat: -12.058404,
    lng: -77.021436,
    address: 'Avenida Almirante Miguel Grau 854',
    district: '',
    phone: '(01) 215-8838',
    insurance: ['SIS', 'SOAT'],
    trauma: true,
    pediatria: true,
    notes: 'Solo pediatría',
  },
  {
    id: 'hospital_mar_a_auxiliadora',
    name: 'Hospital María Auxiliadora',
    short: 'María Auxiliadora',
    type: 'hospital_publico',
    lat: -12.161098,
    lng: -76.958259,
    address: 'Avenida Miguel Iglesias 968',
    district: '',
    phone: '(01) 217-1818',
    insurance: ['SIS', 'SOAT'],
    trauma: true,
    pediatria: true,
    notes: 'Referencia sur de Lima',
  },
  {
    id: 'hospital_santa_rosa',
    name: 'Hospital Santa Rosa',
    short: 'Santa Rosa',
    type: 'hospital_publico',
    lat: -12.072356,
    lng: -77.061028,
    address: 'Avenida Simón Bolívar 800',
    district: '',
    phone: '(01) 615-8200',
    insurance: ['SIS', 'SOAT'],
    trauma: true,
    pediatria: true,
    notes: 'Jesús María',
  },
  {
    id: 'instituto_nacional_de_salud_de',
    name: 'Instituto Nacional de Salud del Niño',
    short: 'Salud del Niño',
    type: 'hospital_publico',
    lat: -12.085636,
    lng: -76.992176,
    address: 'Avenida Agustín de la Rosa Toro 1399',
    district: '',
    phone: '(01) 230-0600',
    insurance: ['SIS'],
    trauma: false,
    pediatria: true,
    notes: 'Solo pediatría — referencia nacional',
  },
  {
    id: 'instituto_nacioanal_de_enferme',
    name: 'Instituto Nacioanal de Enfermedades Neoplásicas',
    short: 'Instituto Nacioanal de Enfer',
    type: 'hospital_publico',
    lat: -12.112606,
    lng: -76.998514,
    address: 'Avenida Angamos Este 2520',
    district: '',
    phone: '(01) 201-6500',
    insurance: ['SIS', 'SOAT'],
    trauma: false,
    pediatria: false,
    notes: 'Oncología — INEN',
  },
  {
    id: 'instituto_nacional_cardiovascu',
    name: 'Instituto Nacional Cardiovascular',
    short: 'Cardiovascular',
    type: 'hospital_publico',
    lat: -12.077198,
    lng: -77.040021,
    address: 'Jirón Coronel Cipriano Zegarra 417',
    district: '',
    phone: '(01) 411-1560',
    insurance: ['SIS', 'EsSalud'],
    trauma: true,
    pediatria: false,
    notes: 'Cardiología y cirugía cardiovascular',
  },
  {
    id: 'instituto_nacional_materno_per',
    name: 'Instituto Nacional Materno Perinatal',
    short: 'Materno Perinatal',
    type: 'hospital_publico',
    lat: -12.052298,
    lng: -77.022102,
    address: 'Jirón Santa Rosa 941',
    district: '',
    phone: '(01) 328-1370',
    insurance: ['SIS'],
    trauma: false,
    pediatria: true,
    notes: 'Partos de alto riesgo',
  },
  {
    id: 'hospital_de_emergencias_grau',
    name: 'Hospital de Emergencias Grau',
    short: 'de Emergencias Grau',
    type: 'hospital_publico',
    lat: -12.058889,
    lng: -77.031051,
    address: 'Avenida Almirante Miguel Grau 351',
    district: '',
    phone: '(01) 428-2327',
    insurance: ['SIS', 'SOAT'],
    trauma: true,
    pediatria: false,
  },
  {
    id: 'hospital_guillermo_kael_n_de_l',
    name: 'Hospital Guillermo Kaelín de la Fuente',
    short: 'Guillermo Kaelín de la Fuent',
    type: 'hospital_publico',
    lat: -12.177591,
    lng: -76.940798,
    address: 'Avenida 26 de Noviembre',
    district: '',
    phone: '(01) 205-1200',
    insurance: ['SIS', 'SOAT'],
    trauma: true,
    pediatria: true,
    notes: 'VMT — sur de Lima',
  },
  {
    id: 'hospital_central_fap',
    name: 'Hospital Central FAP',
    short: 'Central FAP',
    type: 'hospital_publico',
    lat: -12.103812,
    lng: -77.029928,
    address: 'Avenida Andrés Aramburú',
    district: '',
    phone: '(01) 513-4300',
    insurance: ['SOAT', 'Particular'],
    trauma: true,
    pediatria: true,
    notes: 'FAP — atiende emergencias SOAT',
  },
  {
    id: 'hospital_nacional_pnp_luis_n',
    name: 'Hospital Nacional PNP Luis N. Saenz',
    short: 'PNP Luis N. Saenz',
    type: 'hospital_publico',
    lat: -12.084973,
    lng: -77.059932,
    address: 'Avenida Brasil 2600',
    district: '',
    insurance: ['SOAT', 'Particular'],
    trauma: true,
    pediatria: false,
    notes: 'PNP — atiende emergencias SOAT',
  },
  {
    id: 'hospital_municipal_de_surco',
    name: 'Hospital Municipal de Surco',
    short: 'Municipal de Surco',
    type: 'hospital_publico',
    lat: -12.144132,
    lng: -77.005818,
    address: 'Jirón Almirante Miguel Grau 309',
    district: '',
    insurance: ['SIS', 'SOAT'],
    trauma: false,
    pediatria: false,
    notes: 'Municipal Surco',
  },
  {
    id: 'cl_nica_anglo_americana',
    name: 'Clínica Anglo Americana',
    short: 'Anglo Americana',
    type: 'clinica_privada',
    lat: -12.074426,
    lng: -76.955974,
    address: 'Avenida La Fontana',
    district: '',
    phone: '(01) 616-8900',
    insurance: ['Rímac', 'Pacífico', 'Mapfre', 'BUPA', 'La Positiva', 'SOAT', 'Particular'],
    trauma: true,
    pediatria: true,
    notes: 'UCI adultos y pediátrica — referencia trauma privado San Isidro',
  },
  {
    id: 'clinica_ricardo_palma',
    name: 'Clinica Ricardo Palma',
    short: 'Ricardo Palma',
    type: 'clinica_privada',
    lat: -12.090712,
    lng: -77.018301,
    address: 'Avenida Javier Prado Este 1066',
    district: '',
    phone: '(01) 224-2224',
    insurance: ['Rímac', 'Pacífico', 'Mapfre', 'BUPA', 'La Positiva', 'SOAT', 'Particular'],
    trauma: true,
    pediatria: true,
  },
  {
    id: 'cl_nica_el_golf',
    name: 'Clínica El Golf',
    short: 'El Golf',
    type: 'clinica_privada',
    lat: -12.098462,
    lng: -77.051787,
    address: 'Avenida Aurelio Miro Quesada 1030',
    district: '',
    phone: '(01) 635-5000',
    insurance: ['Rímac', 'Pacífico', 'Mapfre', 'BUPA', 'La Positiva', 'SOAT', 'Particular'],
    trauma: true,
    pediatria: true,
    notes: 'San Isidro — UCI adultos',
  },
  {
    id: 'cl_nica_delgado',
    name: 'Clínica Delgado',
    short: 'Delgado',
    type: 'clinica_privada',
    lat: -12.113134,
    lng: -77.033001,
    address: 'Calle General Borgoño 400',
    district: '',
    phone: '(01) 377-7000',
    insurance: ['Rímac', 'Pacífico', 'Mapfre', 'BUPA', 'La Positiva', 'SOAT', 'Particular'],
    trauma: true,
    pediatria: true,
    notes: 'Miraflores — UCI, trauma',
  },
  {
    id: 'cl_nica_good_hope',
    name: 'Clínica Good Hope',
    short: 'Good Hope',
    type: 'clinica_privada',
    lat: -12.125621,
    lng: -77.034518,
    address: 'Malecón Balta 956',
    district: '',
    phone: '(01) 610-7300',
    insurance: ['Rímac', 'Pacífico', 'Mapfre', 'BUPA', 'La Positiva', 'SOAT', 'Particular'],
    trauma: true,
    pediatria: true,
    notes: 'Miraflores — UCI',
  },
  {
    id: 'cl_nica_aliada',
    name: 'Clínica Aliada',
    short: 'Aliada',
    type: 'clinica_privada',
    lat: -12.106168,
    lng: -77.010859,
    address: 'Avenida José Galvez Barrenechea 1044',
    district: '',
    phone: '(01) 650-5000',
    insurance: ['Rímac', 'Pacífico', 'Mapfre', 'BUPA', 'La Positiva', 'SOAT', 'Particular'],
    trauma: true,
    pediatria: true,
    notes: 'San Borja — oncología + emergencias',
  },
  {
    id: 'cl_nica_sanna_san_borja',
    name: 'Clínica SANNA San Borja',
    short: 'SANNA San Borja',
    type: 'clinica_privada',
    lat: -12.092023,
    lng: -77.008338,
    address: 'Avenida Guardia Civil 337',
    district: '',
    phone: '(01) 635-5000',
    insurance: ['Rímac', 'Pacífico', 'Mapfre', 'BUPA', 'La Positiva', 'SOAT', 'Particular'],
    trauma: true,
    pediatria: true,
  },
  {
    id: 'cl_nica_internacional',
    name: 'Clínica Internacional',
    short: 'Internacional',
    type: 'clinica_privada',
    lat: -12.050419,
    lng: -77.036837,
    address: 'Avenida Nicolás de Pierola 733',
    district: '',
    phone: '(01) 619-6161',
    insurance: ['Rímac', 'Pacífico', 'Mapfre', 'La Positiva', 'SOAT', 'Particular'],
    trauma: true,
    pediatria: false,
    notes: 'Varias sedes',
  },
  {
    id: 'cl_nica_internacional___medice',
    name: 'Clínica Internacional - Medicentro San Isidro',
    short: 'Internacional - Medicentro S',
    type: 'clinica_privada',
    lat: -12.093078,
    lng: -77.023959,
    address: 'Avenida Paseo de la República 3058',
    district: '',
    phone: '(01) 619-6161',
    insurance: ['Rímac', 'Pacífico', 'Mapfre', 'La Positiva', 'SOAT', 'Particular'],
    trauma: false,
    pediatria: false,
    notes: 'San Isidro',
  },
  {
    id: 'clinica_internacional',
    name: 'Clinica Internacional',
    short: 'Internacional',
    type: 'clinica_privada',
    lat: -12.058464,
    lng: -77.038667,
    address: 'Avenida Garcilazo de la Vega 1420',
    district: '',
    phone: '(01) 619-6161',
    insurance: ['Rímac', 'Pacífico', 'Mapfre', 'La Positiva', 'SOAT', 'Particular'],
    trauma: true,
    pediatria: false,
  },
  {
    id: 'cl_nica_javier_prado',
    name: 'Clínica Javier Prado',
    short: 'Javier Prado',
    type: 'clinica_privada',
    lat: -12.091103,
    lng: -77.028451,
    address: 'Avenida Javier Prado Este 499',
    district: '',
    phone: '(01) 211-4141',
    insurance: ['Rímac', 'Pacífico', 'Mapfre', 'BUPA', 'La Positiva', 'SOAT', 'Particular'],
    trauma: true,
    pediatria: true,
  },
  {
    id: 'clinica_san_felipe',
    name: 'Clinica San Felipe',
    short: 'San Felipe',
    type: 'clinica_privada',
    lat: -12.086036,
    lng: -77.054338,
    address: 'Avenida Gregorio Escobedo 650',
    district: '',
    phone: '(01) 219-0000',
    insurance: ['Rímac', 'Pacífico', 'Mapfre', 'BUPA', 'La Positiva', 'SOAT', 'Particular'],
    trauma: true,
    pediatria: true,
    notes: 'Jesús María — UCI, pediatría',
  },
  {
    id: 'clinica_centenario_peruano_jap',
    name: 'Clinica Centenario Peruano Japonesa',
    short: 'Centenario Peruano Japonesa',
    type: 'clinica_privada',
    lat: -12.073056,
    lng: -77.059471,
    address: 'Avenida Paso de los Andes 675',
    district: '',
    phone: '(01) 208-8000',
    insurance: ['Rímac', 'Pacífico', 'Mapfre', 'SOAT', 'Particular'],
    trauma: true,
    pediatria: false,
    notes: 'Pueblo Libre',
  },
  {
    id: 'clinica_miraflores',
    name: 'Clinica Miraflores',
    short: 'Miraflores',
    type: 'clinica_privada',
    lat: -12.127228,
    lng: -77.01354,
    address: 'Avenida Alfredo Benavides',
    district: '',
    phone: '(01) 610-9696',
    insurance: ['Rímac', 'Pacífico', 'Mapfre', 'SOAT', 'Particular'],
    trauma: true,
    pediatria: false,
  },
  {
    id: 'clinica_san_borja',
    name: 'Clinica San Borja',
    short: 'San Borja',
    type: 'clinica_privada',
    lat: -12.108738,
    lng: -77.006429,
    address: '',
    district: '',
    insurance: ['Rímac', 'Pacífico', 'SOAT', 'Particular'],
    trauma: true,
    pediatria: false,
  },
  {
    id: 'clinica_inmater',
    name: 'Clinica Inmater',
    short: 'Inmater',
    type: 'clinica_privada',
    lat: -12.096213,
    lng: -77.010802,
    address: 'Avenida Guardia Civil 655',
    district: '',
    phone: '(01) 476-2727',
    insurance: ['Rímac', 'Pacífico', 'SOAT', 'Particular'],
    trauma: false,
    pediatria: true,
    notes: 'Maternidad privada',
  },
  {
    id: 'cl_nica_santa_mar_a',
    name: 'Clínica Santa María',
    short: 'Santa María',
    type: 'clinica_privada',
    lat: -12.103427,
    lng: -77.026207,
    address: 'Calle Las Aguilas 360',
    district: '',
    phone: '(01) 421-6860',
    insurance: ['Rímac', 'Pacífico', 'Mapfre', 'SOAT', 'Particular'],
    trauma: false,
    pediatria: true,
    notes: 'Pediatría — Surco',
  },
  {
    id: 'cl_nica_maison_de_sant',
    name: 'Clínica Maison de Santé',
    short: 'Maison de Santé',
    type: 'clinica_privada',
    lat: -12.157242,
    lng: -77.022443,
    address: 'Avenida Chorrillos 171',
    district: '',
    insurance: ['Rímac', 'Pacífico', 'Mapfre', 'SOAT', 'Particular'],
    trauma: true,
    pediatria: false,
    notes: 'Chorrillos',
  },
  {
    id: 'cl_nica_continental',
    name: 'Clínica Continental',
    short: 'Continental',
    type: 'clinica_privada',
    lat: -12.101551,
    lng: -77.003721,
    address: 'Avenida San Borja Sur 526',
    district: '',
    phone: '(01) 225-1665',
    insurance: ['Rímac', 'Pacífico', 'SOAT', 'Particular'],
    trauma: false,
    pediatria: false,
    notes: 'San Borja',
  },
  {
    id: 'cl_nica_la_luz',
    name: 'Clínica La Luz',
    short: 'La Luz',
    type: 'clinica_privada',
    lat: -12.076278,
    lng: -77.035938,
    address: 'Avenida Arequipa 1148',
    district: '',
    phone: '(01) 613-9292',
    insurance: ['Rímac', 'Pacífico', 'Mapfre', 'SOAT', 'Particular'],
    trauma: true,
    pediatria: false,
    notes: 'Lince',
  },
  {
    id: 'clinica_vesalio',
    name: 'Clinica Vesalio',
    short: 'Vesalio',
    type: 'clinica_privada',
    lat: -12.106349,
    lng: -77.00738,
    address: '',
    district: '',
    insurance: ['Rímac', 'Pacífico', 'Mapfre', 'BUPA', 'SOAT', 'Particular'],
    trauma: true,
    pediatria: true,
    notes: 'San Borja — UCI, trauma',
  },
  {
    id: 'centro_cl_nico_sanna_la_molina',
    name: 'Centro Clínico Sanna La Molina',
    short: 'Sanna La Molina',
    type: 'clinica_privada',
    lat: -12.090188,
    lng: -76.950571,
    address: '',
    district: '',
    insurance: ['Rímac', 'Pacífico', 'Mapfre', 'BUPA', 'SOAT', 'Particular'],
    trauma: false,
    pediatria: false,
    notes: 'La Molina',
  },
]

export const FACILITY_COLORS: Record<FacilityType, string> = {
  hospital_publico: '#3b82f6',
  hospital_essalud: '#10b981',
  clinica_privada: '#a855f7',
  posta: '#f59e0b',
}

export const INSURANCE_COLORS: Record<InsuranceType, string> = {
  EsSalud: '#10b981',
  SIS: '#3b82f6',
  SOAT: '#f59e0b',
  'Rímac': '#ef4444',
  'Pacífico': '#0ea5e9',
  Mapfre: '#6366f1',
  BUPA: '#84cc16',
  'La Positiva': '#f97316',
  Particular: '#6b7280',
}

export const INSURANCE_LABELS: Record<InsuranceType, string> = {
  EsSalud: 'EsSalud',
  SIS: 'SIS',
  SOAT: 'SOAT',
  'Rímac': 'Rímac',
  'Pacífico': 'Pacífico',
  Mapfre: 'Mapfre',
  BUPA: 'BUPA',
  'La Positiva': 'La Positiva',
  Particular: 'Particular',
}